$primary_paletteKeyColor = a8627a
$secondary_paletteKeyColor = 8e6f78
$tertiary_paletteKeyColor = 986e4b
$neutral_paletteKeyColor = 807477
$neutral_variant_paletteKeyColor = 837377
$background = 191113
$onBackground = efdfe1
$surface = 191113
$surfaceDim = 191113
$surfaceBright = 413739
$surfaceContainerLowest = 140c0e
$surfaceContainerLow = 22191c
$surfaceContainer = 261d20
$surfaceContainerHigh = 31282a
$surfaceContainerHighest = 3c3235
$onSurface = efdfe1
$surfaceVariant = 514347
$onSurfaceVariant = d5c2c6
$inverseSurface = efdfe1
$inverseOnSurface = 372e30
$outline = 9e8c90
$outlineVariant = 514347
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb0c9
$primary = ffb0c9
$onPrimary = 541d33
$primaryContainer = 6f3349
$onPrimaryContainer = ffd9e3
$inversePrimary = 8b4a61
$secondary = e2bdc7
$onSecondary = 422931
$secondaryContainer = 5d424a
$onSecondaryContainer = ffd9e3
$tertiary = efbc94
$onTertiary = 48290c
$tertiaryContainer = b48863
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd9e3
$primaryFixedDim = ffb0c9
$onPrimaryFixed = 3a071e
$onPrimaryFixedVariant = 6f3349
$secondaryFixed = ffd9e3
$secondaryFixedDim = e2bdc7
$onSecondaryFixed = 2b151c
$onSecondaryFixedVariant = 5a3f47
$tertiaryFixed = ffdcc2
$tertiaryFixedDim = efbc94
$onTertiaryFixed = 2e1500
$onTertiaryFixedVariant = 623f20
$term0 = 353434
$term1 = ff4c88
$term2 = ffbbb7
$term3 = ffdedf
$term4 = b3a2d5
$term5 = ea8fb0
$term6 = ffba93
$term7 = efd1d2
$term8 = b39e9e
$term9 = ff81a2
$term10 = ffd3d0
$term11 = fff1f0
$term12 = dcbc93
$term13 = f9a8c1
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedef
$flamingo = fcd9e0
$pink = ffd1e1
$mauve = ffa4d4
$red = fc94b7
$maroon = f3aabf
$peach = ffbcc5
$yellow = ffedec
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f4a3de
$lavender = ffb7e4
$klink = b86dac
$klinkSelection = b86dac
$kvisited = c55d94
$kvisitedSelection = c55c93
$knegative = e84f85
$knegativeSelection = e84f85
$kneutral = ff859b
$kneutralSelection = ff859b
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = efdfe1
$subtext1 = d5c2c6
$subtext0 = 9e8c90
$overlay2 = 8a7a7d
$overlay1 = 76676a
$overlay0 = 635659
$surface2 = 514548
$surface1 = 3f3437
$surface0 = 2c2225
$base = 191113
$mantle = 191113
$crust = 181012
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
