interface=wlan0
driver=nl80211
ssid=NETGEAR07
hw_mode=g
channel=1
beacon_int=100
ieee80211n=1
wmm_enabled=1
ignore_broadcast_ssid=0
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=964a3ac8fba84c8baee1
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
eap_server=1
wps_state=2
ap_setup_locked=1
config_methods=label display push_button keypad
wps_pin_requests=/var/run/hostapd.pin-req
