# ### Hyprland ###
# Apps
$terminal = foot
$browser = firefox
$editor = zeditor
$fileExplorer = pcmanfm-qt

# Gaps
$workspaceGaps = 10
$singleWindowGapsOut = 10

# Window styling
$windowBorderSize = 3

# Misc
$volumeStep = 1  # In percent
$cursorTheme = WhiteSur-cursors


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Shift
$kbMoveWinToWsGroup = Ctrl+Super+Shift

# Window actions
$kbToggleWindowFloating = Super+Shift, F

# Apps
$kbBrowser = Super, B
$kbEditor = Super, E
$kbFileExplorer = Super, N

# Misc
$kbSession = Super+Shift, Escape
$kbShowSidebar = Super, A
