monitor = , 2560x1440@240, auto, 1

exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
exec-once = gsettings set org.gnome.desktop.interface font-name 'Adwaita Sans 11'

input {
    kb_layout = eu
    kb_options = caps:escape,altwin:swap_lalt_lwin

    force_no_accel = true

    scroll_method = on_button_down
    scroll_button = 274

    float_switch_override_focus = 2
}

misc {
    vrr = 3
}

# ######## Window rules ########
windowrule = float true, match:class xarchiver

# ## Shell keybinds
unbind = Super, Super_L, global, caelestia:launcher
bind = Super, Space, global, caelestia:launcher

unbind = Super+Alt, S, movetoworkspace, special:special
bind = Super+Alt, S, global, caelestia:screenshotFreeze  # Capture region (freeze)

unbind = Super+ Shift, S, global, caelestia:screenshotFreeze  # Capture region (freeze)
bind = Super+Shift, S, movetoworkspace, special:special

unbind = Super, G, exec, app2unit -- github-desktop
unbind = Super+Alt, E, exec, app2unit -- nemo
unbind = Ctrl+Alt, Escape, exec, app2unit -- qps
unbind = Ctrl+Alt, V, exec, app2unit -- pavucontrol
bind = Super, Return, exec, app2unit -- $terminal
