# ### Hyprland ###
# Window
$windowOpacity = 0.95
$workspaceGaps = 10
$windowGapsIn = 5
$windowGapsOut = 10
$singleWindowGapsOut = 10
$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 10  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 24
