# ### Hyprland ###
# Window
$windowOpacity = 0.95
$workspaceGaps = 10
$windowGapsIn = 5
$windowGapsOut = 10
$singleWindowGapsOut = 10
$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 1  # In percent
$cursorTheme = WhiteSur-cursors
$cursorSize = 24
$iconTheme = Papirus-Dark
$gtkTheme = adw-gtk3
$font = Adwaita Sans 11
