input {
    kb_layout = eu
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35
    
    force_no_accel = true
    kb_options = caps:escape,altwin:swap_lalt_lwin

    scroll_method = on_button_down
    scroll_button = 274

    follow_mouse = 1
    float_switch_override_focus = 2
    focus_on_close = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        scroll_factor = 0.3
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

